apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n0ise
  name: n0ise
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n0ise
  strategy: {}
  template:
    metadata:
      labels:
        app: n0ise
    spec:
      containers:
      - image: gcr.io/n0ise-385214/n0ise:0.03
        name: n0ise
        imagePullPolicy: IfNotPresent
        resources: {}

  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: n0ise
  name: n0ise
spec:
  type: LoadBalancer
  selector:
    app: n0ise
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999